---
version: "2.1"
services:
  grav:
    image: lscr.io/linuxserver/grav:latest
    container_name: grav
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - $PWD/user:/config/www/user
    ports:
      - 80:80
    restart: unless-stopped
