absolute_urls: false
home:
  alias: /home
pages:
  theme: leighhack
  markdown:
    extra: false
  process:
    markdown: true
    twig: false
cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: g
twig:
  cache: true
  debug: true
  auto_reload: true
  autoescape: false
assets:
  css_pipeline: false
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_minify: true
errors:
  display: true
  log: true
debugger:
  enabled: false
  twig: true
  shutdown:
    close_connection: true
gpm:
  releases: stable
  verify_peer: true
name: 'Leigh Hackspace'
facebook: 'https://www.facebook.com/groups/leighhackspace/'
twitter: 'https://twitter.com/leigh_hackspace'
instagram: 'https://www.instagram.com/leighhackspace'
github: 'https://github.com/leigh-hackspace'
slack: 'https://join.slack.com/t/leighhack/shared_invite/enQtNDYzMjEyMDMxNDExLTE1MWY5N2IwMzdhMzQ0ZWFiNDkyNzJmMGM1ZmFkODcwMGM5ODFmYmI4MjhmM2JiMWEyY2E3NTRjMTQzMzljZWU'
discourse: 'https://discourse.leighhack.org'
mastodon: 'https://mastodon.social/@leigh_hackspace'
address: ''
building-name: 'Leigh Spinners Mill'
town: Leigh
email: info@leighhack.org
addressline-1: ''
address-line-2: ''
building_name: 'Leigh Spinners Mill'
address_line_1: 'Park Lane, Leigh '
postcode: 'WN7 2LB'
address_line_2: ''
buildingname: 'Leigh Spinners Mill (3rd Floor)'
streetname: 'Park Lane'
memberships:
  standard:
    enabled: '1'
    name: Standard
    price: '24'
    link: 'https://pay.gocardless.com/AL00024VQTCKBK'
    desc: 'Our standard membership that gives you instant access to all facilities.'
  patron:
    enabled: '1'
    name: Patron
    price: '30'
    link: 'https://pay.gocardless.com/AL00024VQW2FWQ'
    desc: 'A voluntary higher fee that allows us to grow faster and buy better equipment.'
  concession:
    enabled: '1'
    name: Concession
    price: '18'
    link: 'https://pay.gocardless.com/AL0002BMN4S3AX'
    desc: 'Reduced rate for low-income members, pensioners and students'
special_memberships:
  family:
    enabled: '1'
    name: Family
    price: '40'
    link: 'https://pay.gocardless.com/AL000637J3VZP7'
    desc: 'Family membership'
    desc2: '(2 adults and children)'
  corp:
    enabled: '1'
    name: 'Corporate'
    price: '?'
    link: 'mailto:info@leighhack.org?subject=Corporate%20Membership'
    desc: 'For more info'
    desc2: 'please speak to a Director.'
  friend:
    enabled: '1'
    name: 'Friend'
    price: '5'
    link: 'mailto:info@leighhack.org?subject=Friend%20Of%the%20%20Hackspace '
    desc: 'I want to help but'
    desc2: 'I dont have much freetime'
phone: null
membership_cta: 'Become a member and get instant access to all the facilities at Leigh Hackspace.'
membership_cta_button: 'Join Today'
links_left:
  -
    anchor: 'About Us'
    url: /about
  -
    anchor: 'Our Facilities'
    url: /facilities
  -
    anchor: 'Contact Us'
    url: /contact
footer_links_heading: 'Site Links'
social_links_heading: Socials
opening_times:
  monday:
    name: Monday
    open_time: '10:00'
    close_time: '17:00'
    open: null
  tuesday:
    name: Tuesday
    open_time: '14:00'
    close_time: '20:00'
    open: '1'
  wednesday:
    name: Wednesday
    open_time: '14:00'
    close_time: '21:00'
    open: '1'
  thursday:
    name: Thursday
    open_time: '10:00'
    close_time: '17:00'
    open: null
  friday:
    name: Friday
    open_time: '10:00'
    close_time: '17:00'
    open: null
  saturday:
    name: Saturday
    open_time: '12:00'
    close_time: '17:00'
    open: '1'
  sunday:
    name: Sunday
    open_time: '10:00'
    close_time: '17:00'
    open: null
