# title: Company Details
form:
    title: Hackspace Details
    validation: loose
    fields:

        content:
            type: fieldset
            title: 'Hackspace Details'
            collapsed: false
            collapsible: true
            fields:
                name:
                    type: text
                    label: 'Company Name'
                    size: medium
                
                address:
                    type: section
                    title: 'Address'
                    underline: true

                buildingname:
                    type: text
                    label: 'Building name'
                
                streetname:
                    type: text
                    label: 'Street'
                
                town:
                    type: text
                    label: 'Town'
                
                postcode:
                    type: text
                    label: 'Postcode'

                contact:
                    type: section
                    title: 'Contact Details'
                    underline: true

                email:
                    type: text
                    label: 'Email Address'
                    # placeholder_key: Key
                    placeholder_value: Email Address

                phone:
                    type: text
                    label: 'Phone Number'

        social:
            type: fieldset
            title: 'Social Media Links'
            collapsed: false
            collapsible: true
            fields:

                social_links_heading:
                    type: text
                    style: vertical
                    label: 'Social media footer column heading'
                    validate:
                        required: true
        
                social-link:
                    type: columns
                    fields:
                        column1:
                            type: column
                            fields:
                                facebook:
                                    type: text
                                    style: vertical
                                    label: 'Facebook link'

                                twitter:
                                    type: text
                                    style: vertical
                                    label: 'Twitter link'

                                instagram:
                                    type: text
                                    style: vertical
                                    label: 'Instagram link'

                                mastodon:
                                    type: text
                                    style: vertical
                                    label: 'Mastodon link'
                        column2:
                            type: column
                            fields:
                                github:
                                    type: text
                                    style: vertical
                                    label: 'Github link'

                                slack:
                                    type: text
                                    style: vertical
                                    label: 'Slack invite link'

                                discourse:
                                    type: text
                                    style: vertical
                                    label: 'Discourse link'

        membership:
            type: fieldset
            title: 'Membership Pricing'
            collapsed: false
            collapsible: true
            fields:
            
                member_cols:
                    type: columns
                    fields:
                        column1:
                            type: column
                            fields:

                                membership-pricing:
                                    type: section
                                    underline: true
                                  
                                standard:
                                  type: section
                                  title: "Standard"
                                  bold: true

                              
                                memberships.standard.price:
                                    style: vertical
                                    type: text
                                    label: Price
                               
                                memberships.standard.link:
                                    style: vertical
                                    type: text
                                    label: Link

                                memberships.standard.enabled: 
                                    style: vertical
                                    type: checkbox
                                    label: Enabled

                                patron:
                                  type: section
                                  title: "Patron"
                                  bold: true
                                      
                                memberships.patron.price:
                                    style: vertical
                                    type: text
                                    label: Price
                               
                                memberships.patron.link:
                                    style: vertical
                                    type: text
                                    label: Link

                                memberships.patron.enabled: 
                                    style: vertical
                                    type: checkbox
                                    label: Enabled

                                concession:
                                  type: section
                                  title: "Concession"
                                  bold: true

                                memberships.concession.price:
                                    style: vertical
                                    type: text
                                    label: Price
                               
                                memberships.concession.link:
                                    style: vertical
                                    type: text
                                    label: Link

                                memberships.concession.enabled: 
                                    style: vertical
                                    type: checkbox
                                    label: Enabled
                                
                                family:
                                    type: section
                                    title: "Family Membership"
                                    bold: true

                                special_memberships.family.price:
                                    style: vertical
                                    type: text
                                    label: Price

                                special_memberships.family.link:
                                    style: vertical
                                    type: text
                                    label: Link

                                special_memberships.family.enabled:
                                    style: vertical
                                    type: checkbox
                                    label: Enabled

                                daymembership:
                                  type: section
                                  title: "Day Pass"
                                  bold: true

                                special_memberships.daypass.price:
                                    style: vertical
                                    type: text
                                    label: Price
                                
                                special_memberships.daypass.link:
                                    style: vertical
                                    type: text
                                    label: Link
                                
                                special_memberships.daypass.enabled:
                                    style: vertical
                                    type: checkbox
                                    label: Enabled
                                
                                corpmembership:
                                  type: section
                                  title: "Corporate"
                                  bold: true

                                special_memberships.corp.price:
                                    style: vertical
                                    type: text
                                    label: Price
                                
                                special_memberships.corp.link:
                                    style: vertical
                                    type: text
                                    label: Link
                                
                                special_memberships.corp.enabled:
                                    style: vertical
                                    type: checkbox
                                    label: Enabled
                        
                
        opening_times:
            type: fieldset
            title: 'Opening Times'
            collapsed: false
            collapsible: true
            fields:     
                monday:
                    type: section
                    title: "Monday"
                    fields:                    
                        opening_times.monday.open_time:
                            style: vertical
                            type: text
                            label: Open Time (24HR)
                            
                        opening_times.monday.close_time:
                            style: vertical
                            type: text
                            label: Close Time (24HR)
                            
                        opening_times.monday.open:
                            style: vertical
                            type: checkbox
                            label: Open

                tuesday:
                    type: section
                    title: "Tuesday"
                    fields:                    
                        opening_times.tuesday.open_time:
                            style: vertical
                            type: text
                            label: Open Time (24HR)
                            
                        opening_times.tuesday.close_time:
                            style: vertical
                            type: text
                            label: Close Time (24HR)
                            
                        opening_times.tuesday.open:
                            style: vertical
                            type: checkbox
                            label: Open

                wednesday:
                    type: section
                    title: "Wednesday"
                    fields:                    
                        opening_times.wednesday.open_time:
                            style: vertical
                            type: text
                            label: Open Time (24HR)
                            
                        opening_times.wednesday.close_time:
                            style: vertical
                            type: text
                            label: Close Time (24HR)
                            
                        opening_times.wednesday.open:
                            style: vertical
                            type: checkbox
                            label: Open

                thursday:
                    type: section
                    title: "Thursday"
                    fields:                    
                        opening_times.thursday.open_time:
                            style: vertical
                            type: text
                            label: Open Time (24HR)
                            
                        opening_times.thursday.close_time:
                            style: vertical
                            type: text
                            label: Close Time (24HR)
                            
                        opening_times.thursday.open:
                            style: vertical
                            type: checkbox
                            label: Open

                friday:
                    type: section
                    title: "Friday"
                    fields:                    
                        opening_times.friday.open_time:
                            style: vertical
                            type: text
                            label: Open Time (24HR)
                            
                        opening_times.friday.close_time:
                            style: vertical
                            type: text
                            label: Close Time (24HR)
                            
                        opening_times.friday.open:
                            style: vertical
                            type: checkbox
                            label: Open

                saturday:
                    type: section
                    title: "Saturday"
                    fields:                    
                        opening_times.saturday.open_time:
                            style: vertical
                            type: text
                            label: Open Time (24HR)
                            
                        opening_times.saturday.close_time:
                            style: vertical
                            type: text
                            label: Close Time (24HR)
                            
                        opening_times.saturday.open:
                            style: vertical
                            type: checkbox
                            label: Open

                sunday:
                    type: section
                    title: "Sunday"
                    fields:                    
                        opening_times.sunday.open_time:
                            style: vertical
                            type: text
                            label: Open Time (24HR)
                            
                        opening_times.sunday.close_time:
                            style: vertical
                            type: text
                            label: Close Time (24HR)
                            
                        opening_times.sunday.open:
                            style: vertical
                            type: checkbox
                            label: Open


            
        footer: 
            type: fieldset
            title: 'Footer Navigation Links'
            collapsed: false
            collapsible: true
            fields:

                footer_links_heading:
                    type: text
                    style: vertical
                    label: 'Footer links heading'
                    validate:
                        required: true

                footer_cols:
                    type: columns
                    fields:

                        column1:
                            type: column
                            fields:

                                col_left:
                                    type: fieldset
                                    title: 'First column'
                                    collapsed: false
                                    collapsible: true
                                    fields:

                                        links_left:
                                            name: buttons
                                            type: list
                                            style: vertical
                                            label: 'Page links'
                                            fields:
                                                .anchor:
                                                    type: text
                                                    label: Text
                                                .url:
                                                    type: pages
                                                    label: URL

                        column2:
                            type: column
                            fields:

                                col_right:
                                    type: fieldset
                                    title: 'Second column'
                                    collapsed: false
                                    collapsible: true
                                    fields:

                                        links_right:
                                            name: buttons
                                            type: list
                                            style: vertical
                                            label: 'Page links'
                                            fields:
                                                .anchor:
                                                    type: text
                                                    label: Text
                                                .url:
                                                    type: pages
                                                    label: URL

